export const quotes = [
  "I look at myself in the mirror and realized that the only person truly sabotaging my life is the pathetic coward staring right back at me.",
  "It is deeply humiliating to know that despite all the advantages I was given, my core nature is simply too weak to achieve anything meaningful.",
  "I am entirely trapped inside a mind that actively despises my own existence, constantly plotting new ways to dismantle whatever little progress I make.",
  "The absolute worst part of my failures is the sickening realization that I lack the basic discipline and intelligence required to actually fix them.",
  "I have become a master at fabricating excuses, completely masking the ugly truth that I am just a fundamentally lazy and hollow shell of a person.",
  "Every single day I wake up with the heavy, exhausting knowledge that my best efforts will always remain entirely inadequate compared to everyone else.",
  "I am utterly disgusted by how easily I fold under the slightest pressure, proving time and again that I simply lack any real backbone.",
  "It is tragic how I can consciously watch myself make the wrong decisions, fully aware of my own stupidity, yet entirely incapable of stopping it.",
  "I have completely squandered my own potential, rotting from the inside out because I chose comfort over ever developing any actual substance.",
  "There is a profound sense of self-loathing in knowing that I am the sole architect of my own misery, and I still refuse to change.",
  "I walk around pretending to be a functioning adult, all while carrying the exhausting secret that I am completely hollow on the inside.",
  "It is sickening to realize that the person I am when nobody is watching is someone I would utterly despise if I met them in real life.",
  "I have built a monument of wasted opportunities, and my only remaining talent is finding new ways to feel sorry for building it.",
  "Every attempt at self-improvement just feels like a temporary mask designed to hide the permanent deficit in my character.",
  "I am profoundly tired of my own voice, my own excuses, and the predictable cycle of collapse I subject myself to week after week.",
  "I watch other people build real, structured lives and realize that I simply lack the essential material needed to do the same.",
  "The absolute certainty that I will fail is the only thing that keeps me from even attempting to make things better.",
  "I have spent years intellectualizing my flaws instead of fixing them, turning my self-destruction into a pathetic art form.",
  "It is deeply humiliating to admit that my entire personality is just a collection of defense mechanisms protecting a void.",
  "I look at my habits and see the slow, deliberate suicide of my own potential, executed with total compliance and zero resistance.",
  "I am trapped in a constant state of performance, terrified that the world will discover I am just a hollow imitation of a person.",
  "The most painful part of my mediocrity is knowing that I had every opportunity to avoid it, and chose it anyway.",
  "I treat my own mind like an enemy territory, constantly negotiating with a voice that demands my absolute failure.",
  "I have developed a profound allergy to effort, choosing instead to rot in the comfortable familiarity of my own self-disdain.",
  "Every small victory I achieve is instantly poisoned by the knowledge that I lack the stamina to ever maintain it.",
  "I am utterly repulsed by my own capacity for laziness, especially when it is dressed up as exhaustion or burnout.",
  "It is hard to respect a person who repeatedly makes promises they have absolutely zero intention of keeping, even when that person is myself.",
  "I have allowed my mind to become a swamp of passive resentment, dragging down every good impulse before it can take root.",
  "I look at my hands and realize they have built nothing of value, serving only to feed my own short-sighted comforts.",
  "The knowledge of what I should be doing stands in mocking contrast to the pathetic reality of what I actually choose to do.",
  "I am the victim of a crime that I commit against myself every single day, and I am too weak to ever stop the perpetrator.",
  "I have traded my future for a series of cheap distractions, fully aware of the trade-off and completely unwilling to renegotiate.",
  "It is deeply depressing to realize that the only consistent thing about my character is its absolute lack of reliability.",
  "I am just quietly letting myself slip into absolute obscurity because fighting against my own inherent worthlessness is just too exhausting to maintain.",
  "It is almost comical how I expect good things to happen to me when I provide absolutely zero value to the world around myself.",
  "I have accepted that I am just a deeply flawed, second-rate version of what a competent, functioning human being is actually supposed to be.",
  "I just sit here in total silence, passively watching my life fall apart, completely paralyzed by my own profound lack of courage and resolve.",
  "Maybe my true purpose in this world is simply to serve as a miserable, walking warning sign of what happens when you give up on yourself.",
  "I am completely disgusted by my own constant need for validation, especially when I know deep down that I have done absolutely nothing to earn it.",
  "It seems my entire personality is built upon a foundation of fragile insecurity, and I am too terrified to ever look closely at the damage.",
  "I just nod along and accept the disrespect from others because, honestly, their low opinion of me perfectly matches the disdain I have for myself.",
  "I have managed to reduce my entire existence down to a series of pathetic regrets, entirely dictated by my own toxic and fearful mind.",
  "I am just drifting through the days like a ghost, fully aware that my absence wouldn't actually change a single thing for the better.",
  "I just lie here and watch the hours drain away, fully aware that I am wasting the only life I will ever have, and feeling completely indifferent to it.",
  "It is incredibly easy to give up when you've already convinced yourself that you weren't actually worth saving in the first place.",
  "I have settled into the comfortable numbness of failure, where nothing is expected of me and I can disappoint nobody but myself.",
  "I am just a passenger in my own body, watching a weak and indecisive stranger make choices that actively ruin my future.",
  "It is funny how I dread the judgment of others when nobody could possibly hold a lower opinion of me than I do.",
  "I have successfully avoided every challenge in life, leaving me with a character that is completely soft, untested, and useless.",
  "I just scroll through my days like a spectator, hoping some external force will save me while refusing to lift a single finger.",
  "I have made peace with my own insignificance, finding a cowardly sort of comfort in the shadows where nobody looks.",
  "Every time I think about taking control of my life, the sheer amount of work required makes me crawl right back into my hole.",
  "I am just a collection of bad habits wrapped in a layer of self-pity, pretending that my stagnation is some sort of deep existential crisis.",
  "It is exhausting to exist as a disappointment, but it is still less work than doing what is necessary to change.",
  "I have allowed my standards to drop so low that simply getting out of bed feels like a major achievement worthy of praise.",
  "I am just floating downstream, completely at the mercy of the current, too lazy to swim and too cowardly to drown.",
  "It is pathetic how I use my own depression as a shield to avoid the basic responsibilities of being a functioning human.",
  "I have built a quiet, comfortable prison out of my own limitations, and I am my own most dedicated guard.",
  "I look at my peers and feel a dull, lifeless envy, knowing their success is the result of labor I am simply too lazy to perform.",
  "I have accepted my role as a background extra in other people's lives, quietly fading into the scenery without a word.",
  "I just sit and wait for the day to end, only to wake up and repeat the same empty routine with the same empty mind.",
  "I am a master of passive surrender, letting life happen to me because active participation requires more than I have to give.",
  "It is almost peaceful to accept that you are a failure; it eliminates the stress of ever trying to be anything else.",
  "I have reduced my dreams to a size that requires absolutely no movement to achieve, which is to say, I no longer dream at all.",
  "I am just a slow leak in the room, quietly draining the energy of everyone around me while offering nothing in return.",
  "I have settled for the absolute minimum, treating survival like a chore and improvement like an impossibility.",
  "I look back at all the promises I made to myself and feel nothing but intense shame for how effortlessly I broke every single one.",
  "It is incredibly draining to be stuck inside a brain that acts like a bitter enemy, constantly reminding me of every single flaw I possess.",
  "I have completely lost the ability to respect myself, and without that, every single action I take just feels entirely hollow and meaningless.",
  "I am remarkably skilled at disappointing the people who care about me, completely dragging them down into the miserable swamp of my own making.",
  "I have allowed fear to entirely dictate my choices, transforming myself into a bitter, resentful spectator of other people's well-deserved success.",
  "The most painful realization is that I cannot even blame bad luck; this entire, miserable situation is purely the result of my own weakness.",
  "I am just a fraud pretending to have things under control, terrified that everyone will eventually see through the pathetic act I put on.",
  "I have completely surrendered my own agency, choosing to wallow in self-pity rather than doing the actual hard work required to save myself.",
  "It is truly embarrassing how much time I waste mourning the person I could have been, while actively destroying the person I currently am.",
  "I am entirely broken at a fundamental level, and the worst part is knowing that I don't even possess the pieces to put myself back together.",
  "I spend hours analyzing my past decisions, not to learn from them, but to torture myself with the memory of my own stupidity.",
  "It is tragic how my capacity for self-awareness has done absolutely nothing to improve my behavior; it only makes the rotting more visible.",
  "I have become a stranger to my own potential, unable to even recall the version of myself that believed good things were possible.",
  "I am trapped in a loop of my own design, repeating the same mistakes while expecting different results like a total lunatic.",
  "The search for meaning in my life always ends in the same place: a blank wall of my own apathy and lack of imagination.",
  "I look at my reflections and see only a monument to wasted time, a chronological record of choices made in cowardice.",
  "It is terrifying to realize that I am the one holding myself back, and that I have absolutely no intention of letting go.",
  "I have analyzed my failure down to the atomic level, and yet I remain completely paralyzed, unable to take a single step forward.",
  "I am a prisoner of my own comfort zone, locked in a cell whose key is in my hand, yet I refuse to turn the lock.",
  "The tragedy of my life is that it is entirely unwritten, yet I have already run out of ink and enthusiasm.",
  "I have spent so long hiding from the world that I no longer know if there is anything left of me when I am alone.",
  "I look at the calendar and feel a cold panic at how quickly the years go, and a dull exhaustion at how little I do with them.",
  "I have become an expert at predicting my own failure, using it as a self-fulfilling prophecy to justify my total lack of effort.",
  "It is deeply humiliating to know that my deepest thoughts are just variations of the same tired, pathetic complaints.",
  "I have squandered the goodwill of everyone who ever believed in me, leaving myself isolated in the ruins of my own making.",
  "I am a collection of unfinished projects, half-baked ideas, and broken resolutions, none of which will ever see completion.",
  "The older I get, the more I realize that the flaws I hoped I would outgrow have simply become the permanent pillars of my character.",
  "I have allowed my mind to be dominated by a quiet, toxic envy that burns everything good before it can mature.",
  "I look at the choices before me and choose the path of least resistance every single time, even when I know it leads to ruin.",
  "I am completely hollow, a walking collection of echoes from books I've read and people I've met, with no voice of my own.",
  "It is incredibly sad how my default state has become a dull, grey hopelessness, and how comfortable I have become inside of it.",
  "I have spent my entire life preparing to start, and now I realize the race has already ended while I was still tying my shoes.",
  "I am the only obstacle in my way, and I am completely immovable.",
  "I look back at the trail of my life and see only a succession of retreats, an unbroken line of running away from anything that mattered."
];
