-- Legacy widget migration is complete.
-- The old standalone widget source databases were retired after the
-- JeffersonWM-owned widget tables were verified live.
--
-- Keep this file as a checkpoint note only:
-- 1. Run widget-schema.sql for any fresh widget database.
-- 2. Restore data from SQL backups if a historical rebuild is ever needed.
-- 3. Do not recreate the retired standalone dates/fonts databases for normal use.
